// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn0PSCV75xzG_scC0kGoCtBcApUUYhD7w',
    appId: '1:613454711754:web:d671a70acca01092ad5d33',
    messagingSenderId: '613454711754',
    projectId: 'auto-shopping-list-651a9',
    authDomain: 'auto-shopping-list-651a9.firebaseapp.com',
    storageBucket: 'auto-shopping-list-651a9.appspot.com',
    measurementId: 'G-1Y8JVD8L5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqcWK8W2ql8pN81pCA_VHBmvdXV9-3WjA',
    appId: '1:613454711754:android:9ed8817c0eff6256ad5d33',
    messagingSenderId: '613454711754',
    projectId: 'auto-shopping-list-651a9',
    storageBucket: 'auto-shopping-list-651a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiFby4ZxHrOhA-9Y0QDYVbsOlJ0NAEOks',
    appId: '1:613454711754:ios:e9c9cc02151cbd08ad5d33',
    messagingSenderId: '613454711754',
    projectId: 'auto-shopping-list-651a9',
    storageBucket: 'auto-shopping-list-651a9.appspot.com',
    iosClientId: '613454711754-duqq42lt6arln7ddtpsm3837p6iu50f3.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoShoppingListClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiFby4ZxHrOhA-9Y0QDYVbsOlJ0NAEOks',
    appId: '1:613454711754:ios:e9c9cc02151cbd08ad5d33',
    messagingSenderId: '613454711754',
    projectId: 'auto-shopping-list-651a9',
    storageBucket: 'auto-shopping-list-651a9.appspot.com',
    iosClientId: '613454711754-duqq42lt6arln7ddtpsm3837p6iu50f3.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoShoppingListClient',
  );
}
